title: bugthing puts notes on the web
email: benjamin2473565@hotmail.com
description: >
  Sometimes I do stuff on my computer and I want
  to make a reference for me to check in the future.
  This is that thing.
baseurl: ""
url: ""
twitter_username: bugthing
github_username: bugthing
repository: bugthing/bugthing.github.com

# Pagination settings
paginate: 10

# Build settings
markdown: kramdown
gems:
  - jekyll-paginate
exclude:
  - Gemfile
  - Gemfile.lock
  - bin
